[0.158s] Invoking command in '/home/navlab-tx2-4/px4_ros_com_ros2/build/px4_msgs': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/navlab-tx2-4/px4_ros_com_ros2/install/multi_rtd:/opt/ros/eloquent /usr/bin/cmake --build /home/navlab-tx2-4/px4_ros_com_ros2/build/px4_msgs -- -j4 -l4
[2.109s] [  0%] Built target px4_msgs__cpp
[2.246s] [ 12%] Built target px4_msgs__rosidl_generator_c
[2.394s] [ 25%] Built target px4_msgs__rosidl_typesupport_introspection_cpp
[2.496s] [ 38%] Built target px4_msgs__rosidl_typesupport_fastrtps_cpp
[2.590s] [ 50%] Built target px4_msgs__rosidl_typesupport_introspection_c
[2.806s] [ 63%] Built target px4_msgs__rosidl_typesupport_cpp
[2.872s] [ 75%] Built target px4_msgs__rosidl_typesupport_fastrtps_c
[3.118s] [ 88%] Built target px4_msgs__rosidl_typesupport_c
[3.200s] [ 88%] Built target px4_msgs
[3.314s] [ 88%] Built target px4_msgs__py
[3.839s] [100%] Built target px4_msgs__python
[3.977s] [100%] Built target px4_msgs__rosidl_typesupport_c__pyext
[3.978s] [100%] Built target px4_msgs__rosidl_typesupport_fastrtps_c__pyext
[4.450s] Invoked command in '/home/navlab-tx2-4/px4_ros_com_ros2/build/px4_msgs' returned '0': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/navlab-tx2-4/px4_ros_com_ros2/install/multi_rtd:/opt/ros/eloquent /usr/bin/cmake --build /home/navlab-tx2-4/px4_ros_com_ros2/build/px4_msgs -- -j4 -l4
[19.840s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 61, in build
    environment_callback=add_app_to_cpp)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 110, in build
    if await has_target(args.build_base, 'install'):
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 57, in has_target
    return target in await get_makefile_targets(path)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 78, in get_makefile_targets
    CMAKE_EXECUTABLE, '--build', path, '--target', 'help'], cwd=path)
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['/usr/bin/cmake', '--build', '/home/navlab-tx2-4/px4_ros_com_ros2/build/px4_msgs', '--target', 'help'] to pass: make: *** [help] Interrupt

